name: CI/CD for ReactJS

on:
  push:
    branches:
      - cv-daffa

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 16.13.2

    - name: Install Dependencies
      run: npm install

    - name: Build React App
      run: npm run build

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:      
    - name: SSH into Server and Restart Nginx
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        password: ${{ secrets.SSH_PRIVATE_KEY_PASSPHRASE }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.DEPLOY_PORT }}
        script: |
          sudo systemctl restart nginx
