name: CI/CD for ReactJS App with Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: |
        docker build -t "${{ secrets.DOCKER_USERNAME }}/portofolio-daffa" .
        docker push "${{ secrets.DOCKER_USERNAME }}/portofolio-daffa"

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: SSH into Server and Pull Docker Image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.DEPLOY_PORT }}
        script: |
          sudo -S <<< "${{ secrets.DEPLOY_PASSWORD }}" docker pull "${{ secrets.DOCKER_USERNAME }}/portofolio-daffa"

    - name: SSH into Server and stop Docker Image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.DEPLOY_PORT }}
        script: |
          sudo -S <<< "${{ secrets.DEPLOY_PASSWORD }}" docker stop container-portofolio-daffa || true

    - name: SSH into Server and remove Docker Image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.DEPLOY_PORT }}
        script: |
          sudo -S <<< "${{ secrets.DEPLOY_PASSWORD }}" docker rm container-portofolio-daffa || true

    - name: SSH into Server and deploy Docker Container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.DEPLOY_PORT }}
        script: |
          sudo -S <<< "${{ secrets.DEPLOY_PASSWORD }}" docker run -d --name container-portofolio-daffa -p 8085:8085 "${{ secrets.DOCKER_USERNAME }}/portofolio-daffa"
